
### GET ALL MOVIES

GET http://localhost:3000/movie

### GET MOVIES BY YEAR

GET http://localhost:3000/movie?year=2010

### GET MOVIE BY ID

GET http://localhost:3000/movie/6983534fb16e43e58c8dda72 

### CREATE A NEW MOVIE

POST http://localhost:3000/movie
Content-Type: application/json

{
  "title": "inception",
  "year": 2019
}

### DELETE A MOVIE BY ID

DELETE http://localhost:3000/movie/6983534fb16e43e58c8dda72

### UPDATE A MOVIE BY ID

PUT http://localhost:3000/movie/695adaab5bc9af247d577418
Content-Type: application/json

{
  "title": "The Dark Knight",
  "year": 2013
}

###

